name: BazeliOSLab
options:
  bundleIdPrefix: com.bazelioslab
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [BazeliOSLab]
    dependencies:
        - target: UjadwgichwelqzazfjmcModule 
        - target: FfdxilwacukuginqinzuModule 
        - target: DrifwoawyiarjxhzbafmModule 
        - target: WofcocbyqeeebeztgujnModule 
        - target: TjvzhnvqwvvwctreojlsModule 
        - target: KjjkhpflwszlvkkqpouwModule 
        - target: BgjcbgijbzaetxvqxevxModule 
        - target: AfocreoarxqlslumxtjoModule 
        - target: DnvysrekyoksptjrskqnModule 
        - target: WkjeddciuuvhdkdkanvmModule 
        - target: JdsscacekxvbkgneudwwModule 
    scheme:
      testTargets:
        - MyAppTests
        - UjadwgichwelqzazfjmcModuleTests
        - FfdxilwacukuginqinzuModuleTests
        - DrifwoawyiarjxhzbafmModuleTests
        - WofcocbyqeeebeztgujnModuleTests
        - TjvzhnvqwvvwctreojlsModuleTests
        - KjjkhpflwszlvkkqpouwModuleTests
        - BgjcbgijbzaetxvqxevxModuleTests
        - AfocreoarxqlslumxtjoModuleTests
        - DnvysrekyoksptjrskqnModuleTests
        - WkjeddciuuvhdkdkanvmModuleTests
        - JdsscacekxvbkgneudwwModuleTests
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MyApp
    sources: [BazeliOSLabTests]
  UjadwgichwelqzazfjmcModule:
    type: framework
    platform: iOS
    info:
      path: Modules/UjadwgichwelqzazfjmcModule/Sources/Info.plist
    sources: [Modules/UjadwgichwelqzazfjmcModule/Sources]
  UjadwgichwelqzazfjmcModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/UjadwgichwelqzazfjmcModule/Tests/Info.plist
    sources: [Modules/UjadwgichwelqzazfjmcModule/Tests]
  FfdxilwacukuginqinzuModule:
    type: framework
    platform: iOS
    info:
      path: Modules/FfdxilwacukuginqinzuModule/Sources/Info.plist
    sources: [Modules/FfdxilwacukuginqinzuModule/Sources]
  FfdxilwacukuginqinzuModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/FfdxilwacukuginqinzuModule/Tests/Info.plist
    sources: [Modules/FfdxilwacukuginqinzuModule/Tests]
  DrifwoawyiarjxhzbafmModule:
    type: framework
    platform: iOS
    info:
      path: Modules/DrifwoawyiarjxhzbafmModule/Sources/Info.plist
    sources: [Modules/DrifwoawyiarjxhzbafmModule/Sources]
  DrifwoawyiarjxhzbafmModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/DrifwoawyiarjxhzbafmModule/Tests/Info.plist
    sources: [Modules/DrifwoawyiarjxhzbafmModule/Tests]
  WofcocbyqeeebeztgujnModule:
    type: framework
    platform: iOS
    info:
      path: Modules/WofcocbyqeeebeztgujnModule/Sources/Info.plist
    sources: [Modules/WofcocbyqeeebeztgujnModule/Sources]
  WofcocbyqeeebeztgujnModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/WofcocbyqeeebeztgujnModule/Tests/Info.plist
    sources: [Modules/WofcocbyqeeebeztgujnModule/Tests]
  TjvzhnvqwvvwctreojlsModule:
    type: framework
    platform: iOS
    info:
      path: Modules/TjvzhnvqwvvwctreojlsModule/Sources/Info.plist
    sources: [Modules/TjvzhnvqwvvwctreojlsModule/Sources]
  TjvzhnvqwvvwctreojlsModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/TjvzhnvqwvvwctreojlsModule/Tests/Info.plist
    sources: [Modules/TjvzhnvqwvvwctreojlsModule/Tests]
  KjjkhpflwszlvkkqpouwModule:
    type: framework
    platform: iOS
    info:
      path: Modules/KjjkhpflwszlvkkqpouwModule/Sources/Info.plist
    sources: [Modules/KjjkhpflwszlvkkqpouwModule/Sources]
  KjjkhpflwszlvkkqpouwModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/KjjkhpflwszlvkkqpouwModule/Tests/Info.plist
    sources: [Modules/KjjkhpflwszlvkkqpouwModule/Tests]
  BgjcbgijbzaetxvqxevxModule:
    type: framework
    platform: iOS
    info:
      path: Modules/BgjcbgijbzaetxvqxevxModule/Sources/Info.plist
    sources: [Modules/BgjcbgijbzaetxvqxevxModule/Sources]
  BgjcbgijbzaetxvqxevxModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/BgjcbgijbzaetxvqxevxModule/Tests/Info.plist
    sources: [Modules/BgjcbgijbzaetxvqxevxModule/Tests]
  AfocreoarxqlslumxtjoModule:
    type: framework
    platform: iOS
    info:
      path: Modules/AfocreoarxqlslumxtjoModule/Sources/Info.plist
    sources: [Modules/AfocreoarxqlslumxtjoModule/Sources]
  AfocreoarxqlslumxtjoModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/AfocreoarxqlslumxtjoModule/Tests/Info.plist
    sources: [Modules/AfocreoarxqlslumxtjoModule/Tests]
  DnvysrekyoksptjrskqnModule:
    type: framework
    platform: iOS
    info:
      path: Modules/DnvysrekyoksptjrskqnModule/Sources/Info.plist
    sources: [Modules/DnvysrekyoksptjrskqnModule/Sources]
  DnvysrekyoksptjrskqnModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/DnvysrekyoksptjrskqnModule/Tests/Info.plist
    sources: [Modules/DnvysrekyoksptjrskqnModule/Tests]
  WkjeddciuuvhdkdkanvmModule:
    type: framework
    platform: iOS
    info:
      path: Modules/WkjeddciuuvhdkdkanvmModule/Sources/Info.plist
    sources: [Modules/WkjeddciuuvhdkdkanvmModule/Sources]
  WkjeddciuuvhdkdkanvmModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/WkjeddciuuvhdkdkanvmModule/Tests/Info.plist
    sources: [Modules/WkjeddciuuvhdkdkanvmModule/Tests]
  JdsscacekxvbkgneudwwModule:
    type: framework
    platform: iOS
    info:
      path: Modules/JdsscacekxvbkgneudwwModule/Sources/Info.plist
    sources: [Modules/JdsscacekxvbkgneudwwModule/Sources]
  JdsscacekxvbkgneudwwModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/JdsscacekxvbkgneudwwModule/Tests/Info.plist
    sources: [Modules/JdsscacekxvbkgneudwwModule/Tests]
