name: BazeliOSLab
options:
  bundleIdPrefix: com.bazelioslab
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [BazeliOSLab]
    dependencies:
        - target: YgfwnzhkjdqjkhpijrvyModule 
    scheme:
      testTargets:
        - MyAppTests
        - YgfwnzhkjdqjkhpijrvyModuleTests
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MyApp
    sources: [BazeliOSLabTests]
  YgfwnzhkjdqjkhpijrvyModule:
    type: framework
    platform: iOS
    info:
      path: Modules/YgfwnzhkjdqjkhpijrvyModule/Sources/Info.plist
    sources: [Modules/YgfwnzhkjdqjkhpijrvyModule/Sources]
  YgfwnzhkjdqjkhpijrvyModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/YgfwnzhkjdqjkhpijrvyModule/Tests/Info.plist
    sources: [Modules/YgfwnzhkjdqjkhpijrvyModule/Tests]
