name: BazeliOSLab
options:
  bundleIdPrefix: com.bazelioslab
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [BazeliOSLab]
    dependencies:
        - target: VthqudloiarldralioceModule 
        - target: OcgdlquaarpqgjxhkutuModule 
        - target: NpaclahenvasqastbbuuModule 
        - target: RdasauiarzztsmpmrfxsModule 
        - target: XiwqqdhiulxdmtntopyaModule 
        - target: TzdcbzzwyyxjdjbnfuotModule 
    scheme:
      testTargets:
        - MyAppTests
        - VthqudloiarldralioceModuleTests
        - OcgdlquaarpqgjxhkutuModuleTests
        - NpaclahenvasqastbbuuModuleTests
        - RdasauiarzztsmpmrfxsModuleTests
        - XiwqqdhiulxdmtntopyaModuleTests
        - TzdcbzzwyyxjdjbnfuotModuleTests
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MyApp
    sources: [BazeliOSLabTests]
  VthqudloiarldralioceModule:
    type: framework
    platform: iOS
    info:
      path: Modules/VthqudloiarldralioceModule/Sources/Info.plist
    sources: [Modules/VthqudloiarldralioceModule/Sources]
  VthqudloiarldralioceModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/VthqudloiarldralioceModule/Tests/Info.plist
    sources: [Modules/VthqudloiarldralioceModule/Tests]
  OcgdlquaarpqgjxhkutuModule:
    type: framework
    platform: iOS
    info:
      path: Modules/OcgdlquaarpqgjxhkutuModule/Sources/Info.plist
    sources: [Modules/OcgdlquaarpqgjxhkutuModule/Sources]
  OcgdlquaarpqgjxhkutuModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/OcgdlquaarpqgjxhkutuModule/Tests/Info.plist
    sources: [Modules/OcgdlquaarpqgjxhkutuModule/Tests]
  NpaclahenvasqastbbuuModule:
    type: framework
    platform: iOS
    info:
      path: Modules/NpaclahenvasqastbbuuModule/Sources/Info.plist
    sources: [Modules/NpaclahenvasqastbbuuModule/Sources]
  NpaclahenvasqastbbuuModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/NpaclahenvasqastbbuuModule/Tests/Info.plist
    sources: [Modules/NpaclahenvasqastbbuuModule/Tests]
  RdasauiarzztsmpmrfxsModule:
    type: framework
    platform: iOS
    info:
      path: Modules/RdasauiarzztsmpmrfxsModule/Sources/Info.plist
    sources: [Modules/RdasauiarzztsmpmrfxsModule/Sources]
  RdasauiarzztsmpmrfxsModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/RdasauiarzztsmpmrfxsModule/Tests/Info.plist
    sources: [Modules/RdasauiarzztsmpmrfxsModule/Tests]
  XiwqqdhiulxdmtntopyaModule:
    type: framework
    platform: iOS
    info:
      path: Modules/XiwqqdhiulxdmtntopyaModule/Sources/Info.plist
    sources: [Modules/XiwqqdhiulxdmtntopyaModule/Sources]
  XiwqqdhiulxdmtntopyaModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/XiwqqdhiulxdmtntopyaModule/Tests/Info.plist
    sources: [Modules/XiwqqdhiulxdmtntopyaModule/Tests]
  TzdcbzzwyyxjdjbnfuotModule:
    type: framework
    platform: iOS
    info:
      path: Modules/TzdcbzzwyyxjdjbnfuotModule/Sources/Info.plist
    sources: [Modules/TzdcbzzwyyxjdjbnfuotModule/Sources]
  TzdcbzzwyyxjdjbnfuotModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/TzdcbzzwyyxjdjbnfuotModule/Tests/Info.plist
    sources: [Modules/TzdcbzzwyyxjdjbnfuotModule/Tests]
