name: BazeliOSLab
options:
  bundleIdPrefix: com.bazelioslab
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [BazeliOSLab]
    dependencies:
        - target: VzdgnhvijepsejwvzzrmModule 
        - target: GagnavxuucnyzcwxozalModule 
        - target: AivvdaspcwiuwbcyrqcgModule 
        - target: ZoyhlivdsdqzpiufgvolModule 
        - target: AwltdnylrcrmsyiyhwajModule 
        - target: UnbqqdddupzlwlmpnwyqModule 
        - target: YquuhfpwvlmxfulstehiModule 
        - target: PjofdolefaalkcelbvmiModule 
        - target: AioozazfwizpxjmrgygnModule 
        - target: TrinzdbknacwuxswdflpModule 
        - target: TsvqmznuwumqchghtsphModule 
    scheme:
      testTargets:
        - MyAppTests
        - VzdgnhvijepsejwvzzrmModuleTests
        - GagnavxuucnyzcwxozalModuleTests
        - AivvdaspcwiuwbcyrqcgModuleTests
        - ZoyhlivdsdqzpiufgvolModuleTests
        - AwltdnylrcrmsyiyhwajModuleTests
        - UnbqqdddupzlwlmpnwyqModuleTests
        - YquuhfpwvlmxfulstehiModuleTests
        - PjofdolefaalkcelbvmiModuleTests
        - AioozazfwizpxjmrgygnModuleTests
        - TrinzdbknacwuxswdflpModuleTests
        - TsvqmznuwumqchghtsphModuleTests
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MyApp
    sources: [BazeliOSLabTests]
  VzdgnhvijepsejwvzzrmModule:
    type: framework
    platform: iOS
    info:
      path: Modules/VzdgnhvijepsejwvzzrmModule/Sources/Info.plist
    sources: [Modules/VzdgnhvijepsejwvzzrmModule/Sources]
  VzdgnhvijepsejwvzzrmModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/VzdgnhvijepsejwvzzrmModule/Tests/Info.plist
    sources: [Modules/VzdgnhvijepsejwvzzrmModule/Tests]
  GagnavxuucnyzcwxozalModule:
    type: framework
    platform: iOS
    info:
      path: Modules/GagnavxuucnyzcwxozalModule/Sources/Info.plist
    sources: [Modules/GagnavxuucnyzcwxozalModule/Sources]
  GagnavxuucnyzcwxozalModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/GagnavxuucnyzcwxozalModule/Tests/Info.plist
    sources: [Modules/GagnavxuucnyzcwxozalModule/Tests]
  AivvdaspcwiuwbcyrqcgModule:
    type: framework
    platform: iOS
    info:
      path: Modules/AivvdaspcwiuwbcyrqcgModule/Sources/Info.plist
    sources: [Modules/AivvdaspcwiuwbcyrqcgModule/Sources]
  AivvdaspcwiuwbcyrqcgModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/AivvdaspcwiuwbcyrqcgModule/Tests/Info.plist
    sources: [Modules/AivvdaspcwiuwbcyrqcgModule/Tests]
  ZoyhlivdsdqzpiufgvolModule:
    type: framework
    platform: iOS
    info:
      path: Modules/ZoyhlivdsdqzpiufgvolModule/Sources/Info.plist
    sources: [Modules/ZoyhlivdsdqzpiufgvolModule/Sources]
  ZoyhlivdsdqzpiufgvolModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/ZoyhlivdsdqzpiufgvolModule/Tests/Info.plist
    sources: [Modules/ZoyhlivdsdqzpiufgvolModule/Tests]
  AwltdnylrcrmsyiyhwajModule:
    type: framework
    platform: iOS
    info:
      path: Modules/AwltdnylrcrmsyiyhwajModule/Sources/Info.plist
    sources: [Modules/AwltdnylrcrmsyiyhwajModule/Sources]
  AwltdnylrcrmsyiyhwajModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/AwltdnylrcrmsyiyhwajModule/Tests/Info.plist
    sources: [Modules/AwltdnylrcrmsyiyhwajModule/Tests]
  UnbqqdddupzlwlmpnwyqModule:
    type: framework
    platform: iOS
    info:
      path: Modules/UnbqqdddupzlwlmpnwyqModule/Sources/Info.plist
    sources: [Modules/UnbqqdddupzlwlmpnwyqModule/Sources]
  UnbqqdddupzlwlmpnwyqModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/UnbqqdddupzlwlmpnwyqModule/Tests/Info.plist
    sources: [Modules/UnbqqdddupzlwlmpnwyqModule/Tests]
  YquuhfpwvlmxfulstehiModule:
    type: framework
    platform: iOS
    info:
      path: Modules/YquuhfpwvlmxfulstehiModule/Sources/Info.plist
    sources: [Modules/YquuhfpwvlmxfulstehiModule/Sources]
  YquuhfpwvlmxfulstehiModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/YquuhfpwvlmxfulstehiModule/Tests/Info.plist
    sources: [Modules/YquuhfpwvlmxfulstehiModule/Tests]
  PjofdolefaalkcelbvmiModule:
    type: framework
    platform: iOS
    info:
      path: Modules/PjofdolefaalkcelbvmiModule/Sources/Info.plist
    sources: [Modules/PjofdolefaalkcelbvmiModule/Sources]
  PjofdolefaalkcelbvmiModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/PjofdolefaalkcelbvmiModule/Tests/Info.plist
    sources: [Modules/PjofdolefaalkcelbvmiModule/Tests]
  AioozazfwizpxjmrgygnModule:
    type: framework
    platform: iOS
    info:
      path: Modules/AioozazfwizpxjmrgygnModule/Sources/Info.plist
    sources: [Modules/AioozazfwizpxjmrgygnModule/Sources]
  AioozazfwizpxjmrgygnModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/AioozazfwizpxjmrgygnModule/Tests/Info.plist
    sources: [Modules/AioozazfwizpxjmrgygnModule/Tests]
  TrinzdbknacwuxswdflpModule:
    type: framework
    platform: iOS
    info:
      path: Modules/TrinzdbknacwuxswdflpModule/Sources/Info.plist
    sources: [Modules/TrinzdbknacwuxswdflpModule/Sources]
  TrinzdbknacwuxswdflpModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/TrinzdbknacwuxswdflpModule/Tests/Info.plist
    sources: [Modules/TrinzdbknacwuxswdflpModule/Tests]
  TsvqmznuwumqchghtsphModule:
    type: framework
    platform: iOS
    info:
      path: Modules/TsvqmznuwumqchghtsphModule/Sources/Info.plist
    sources: [Modules/TsvqmznuwumqchghtsphModule/Sources]
  TsvqmznuwumqchghtsphModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/TsvqmznuwumqchghtsphModule/Tests/Info.plist
    sources: [Modules/TsvqmznuwumqchghtsphModule/Tests]
