name: BazeliOSLab
options:
  bundleIdPrefix: com.bazelioslab
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [BazeliOSLab]
    dependencies:
        - target: JxsjzzfuwipukbmdhcqyModule 
        - target: QuhbyghzaycwowspihgsModule 
        - target: MlicwkzhcuswcevotnvoModule 
        - target: OlechosbuexcaujsvrefModule 
        - target: NfxvvhgnxbyyhzghtwscModule 
        - target: XkidjvyydgusqgbcqtsvModule 
    scheme:
      testTargets:
        - MyAppTests
        - JxsjzzfuwipukbmdhcqyModuleTests
        - QuhbyghzaycwowspihgsModuleTests
        - MlicwkzhcuswcevotnvoModuleTests
        - OlechosbuexcaujsvrefModuleTests
        - NfxvvhgnxbyyhzghtwscModuleTests
        - XkidjvyydgusqgbcqtsvModuleTests
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MyApp
    sources: [BazeliOSLabTests]
  JxsjzzfuwipukbmdhcqyModule:
    type: framework
    platform: iOS
    info:
      path: Modules/JxsjzzfuwipukbmdhcqyModule/Sources/Info.plist
    sources: [Modules/JxsjzzfuwipukbmdhcqyModule/Sources]
  JxsjzzfuwipukbmdhcqyModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/JxsjzzfuwipukbmdhcqyModule/Tests/Info.plist
    sources: [Modules/JxsjzzfuwipukbmdhcqyModule/Tests]
  QuhbyghzaycwowspihgsModule:
    type: framework
    platform: iOS
    info:
      path: Modules/QuhbyghzaycwowspihgsModule/Sources/Info.plist
    sources: [Modules/QuhbyghzaycwowspihgsModule/Sources]
  QuhbyghzaycwowspihgsModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/QuhbyghzaycwowspihgsModule/Tests/Info.plist
    sources: [Modules/QuhbyghzaycwowspihgsModule/Tests]
  MlicwkzhcuswcevotnvoModule:
    type: framework
    platform: iOS
    info:
      path: Modules/MlicwkzhcuswcevotnvoModule/Sources/Info.plist
    sources: [Modules/MlicwkzhcuswcevotnvoModule/Sources]
  MlicwkzhcuswcevotnvoModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/MlicwkzhcuswcevotnvoModule/Tests/Info.plist
    sources: [Modules/MlicwkzhcuswcevotnvoModule/Tests]
  OlechosbuexcaujsvrefModule:
    type: framework
    platform: iOS
    info:
      path: Modules/OlechosbuexcaujsvrefModule/Sources/Info.plist
    sources: [Modules/OlechosbuexcaujsvrefModule/Sources]
  OlechosbuexcaujsvrefModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/OlechosbuexcaujsvrefModule/Tests/Info.plist
    sources: [Modules/OlechosbuexcaujsvrefModule/Tests]
  NfxvvhgnxbyyhzghtwscModule:
    type: framework
    platform: iOS
    info:
      path: Modules/NfxvvhgnxbyyhzghtwscModule/Sources/Info.plist
    sources: [Modules/NfxvvhgnxbyyhzghtwscModule/Sources]
  NfxvvhgnxbyyhzghtwscModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/NfxvvhgnxbyyhzghtwscModule/Tests/Info.plist
    sources: [Modules/NfxvvhgnxbyyhzghtwscModule/Tests]
  XkidjvyydgusqgbcqtsvModule:
    type: framework
    platform: iOS
    info:
      path: Modules/XkidjvyydgusqgbcqtsvModule/Sources/Info.plist
    sources: [Modules/XkidjvyydgusqgbcqtsvModule/Sources]
  XkidjvyydgusqgbcqtsvModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/XkidjvyydgusqgbcqtsvModule/Tests/Info.plist
    sources: [Modules/XkidjvyydgusqgbcqtsvModule/Tests]
