name: BazeliOSLab
options:
  bundleIdPrefix: com.bazelioslab
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [BazeliOSLab]
    dependencies:
        - target: QsyxvhuicwpvqrszdcrhModule 
    scheme:
      testTargets:
        - MyAppTests
        - QsyxvhuicwpvqrszdcrhModuleTests
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MyApp
    sources: [BazeliOSLabTests]
  QsyxvhuicwpvqrszdcrhModule:
    type: framework
    platform: iOS
    info:
      path: Modules/QsyxvhuicwpvqrszdcrhModule/Sources/Info.plist
    sources: [Modules/QsyxvhuicwpvqrszdcrhModule/Sources]
  QsyxvhuicwpvqrszdcrhModuleTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/QsyxvhuicwpvqrszdcrhModule/Tests/Info.plist
    sources: [Modules/QsyxvhuicwpvqrszdcrhModule/Tests]
